### ISSUE TITLE
About using MoE

### ISSUE THREAD

**Issue by AlfieDiCaprio** [RoyalSkye/Routing-MVMoE#3]
Thank you for your work and for sharing the code.

I am curious whether the MoE module can be applied to other VRP variants with constraints, and if it functions as a plug-and-play module. I’ve just started learning, and I’m a bit confused about how to use MoE to replace the FFN for solving constrained VRP problems.

**Comment by RoyalSkye** [comment]
Hi, thanks for your interest. Yes, MoE is a general concept and can be used as a plug-and-play module to enhance model capacity, but it's not intended to address constraints. It (sparsely) widens the network by duplicating a layer into multiple layers, allowing inputs to adaptively pass through selected ones via a gating network. See [here](https://github.com/RoyalSkye/Routing-MVMoE/blob/main/models/MOEModel.py#L203) regarding how to replace FFN with MoE. If you are working with autoregressive construction solvers (e.g., AM, POMO), their decoders typically handle constraints through feasibility masking. As long as your base model can solve constrained VRPs, the MoE variant will be able to handle them as well.

**Comment by AlfieDiCaprio** [comment]
Thanks for the explanation!! I will try it

**Comment by AlfieDiCaprio** [comment]
Hi, sorry to bother you again, I am still exploring and learning your work. If I just want to target the **OVRPTW** problem and not use MoE, when I set problem to "OVRPTW", num_experts to 1, it seems to be possible? 

But if I want to try more nodes (for example, n=500), I first use generate_data to generate the OVRPTW_500 dataset. Then, due to the usage restrictions of `get_opt_sol_path`, I use the following code to generate the optimal solution based on baseline -> or_tools:
`python OR-Tools_baseline.py --problem=OVRPTW --datasets=../data/CVRPTW/ovrptw500_uniform.pkl -n=1000 --cpus=32 -timelimit=20`
But the following two problems occurred:
1. When using CPU:
```
Traceback (most recent call last):
File "/opt/anaconda3/envs/ctsp/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/opt/anaconda3/envs/ctsp/lib/python3.9/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/opt/anaconda3/envs/ctsp/lib/python3.9/multiprocessing/pool.py", line 114, in worker
task = get()
File "/opt/anaconda3/envs/ctsp/lib/python3.9/multiprocessing/queues.py", line 367, in get
return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'run_func' on <module '__mp_main__' from '/Users/xxx/Documents/SEU/Paper/code/Neural/Routing-MVMoE-main-2/baselines/OR-Tools_baseline.py'>
```
2. When using GPU (according to the display, each round of calculation is failed):
```
Traceback (most recent call last):
File "/root/Routing-MVMoE-main/baselines/OR-Tools_baseline.py", line 421, in <module> print("Average cost: {} +- {}".format(np.mean(costs), 2 * np.std(costs) / np.sqrt(len(costs)))) 
File "/root/miniforge3/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 3504, in mean return _methods._mean(a, axis=axis, dtype=dtype, 
File "/root/miniforge3/lib/python3.10/site-packages/numpy/core/_methods.py", line 118, in _mean ret = umr_sum(arr, axis, dtype, out, keepdims, where=where) 
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```
I would like to ask how to correctly use or-tools to generate the optimal solution? Thank you so much!
